### ISSUE TITLE
Solver does not converge for solving throat discontinuity

### ISSUE THREAD

**Issue by TheOfficialDarthVader** [DavidPoves/11-Parameters-Turbine-Blade-Generator#1]
Running:

```python
radius = 5.5
axial_chord = 1.102
tangential_chord = 0.591
unguided_turning = 6.5
inlet_blade = 35 * np.pi/180
inlet_half_wedge = 9 * np.pi/180
le_r = 0.0310
outlet_blade = 57 * np.pi/180
te_r = 0.0160
n_blades = 51
throat = 0.337

blade = TurbineBladeGen(radius, axial_chord, tangential_chord, unguided_turning, inlet_blade, inlet_half_wedge, le_r,
	             outlet_blade, te_r, n_blades, throat)

blade.calculate_blade_geometry()
```

The code gets stuck in the while loop for removing the throat discontinuity. `abs(self.y2 - yy2)` does not get any smaller than 1.96. My input parameters are taken from "An Eleven Parameter Axial
Turbine Airfoil Geometry Model" By L. J. Pritchard. I've changed the outlet blade angle to be 57 not -57 as is stated in the paper as that gives an erroneous value for `yy2`.

I can't figure out why the code doesn't converge, if you could give some insight on the input parameters that would be really helpful.

**Comment by DavidPoves** [comment]
Hey!

First of all, thanks for sharing your problem.
Regarding your particular issue, you may check the input parameters from Figure 19 of Pritchard's paper. There you may see that the author is using -57 degrees, which corresponds to BETA OUT. Moreover, if you take a look at how this angle is defined, it should always be negative (see Figure 1). Taking this angle to be positive results in a non sense outlet, thus no convergence is achieved.

I hope I could solve your issue. If so, I will close the issue.

Have a nice day!

**Comment by TheOfficialDarthVader** [comment]
While I was writing that previous post I had a thought about the unguided turning. I believe it is actually a percentage (couldn't see anything about that in Pritchard's paper). So setting `unguided_turning = 6.5/100` and `outlet_blade = -57 * np.pi/180` gives a result which looks to match the example given in Pritchard's paper.

**Comment by DavidPoves** [comment]
The unguided turning is an angle, which should be expressed in radians. Hence, `unguided_turning = 6.5 * np.pi/180`

**Comment by TheOfficialDarthVader** [comment]
Now that I've just tried that it works, it didn't work when I originally tried it...

**Comment by DavidPoves** [comment]
Cool! Have a nice day.
